[emulation]
    # Disable the boot sequence and boot directly into the ROM ?
    skip_bios = false

[display]
    width        = 800
    height       = 600
    force_aspect = true
    show_fps     = false

[input]
    [input.keyboard]
    # TODO : multiple bindings ? (with 1 list per gameboy key...)
    # TODO : enforce binding uniqueness (1 keyboard key = 1 gameboy key at most)
    Up     = "Up"
    Down   = "Down"
    Left   = "Left"
    Right  = "Right"
    Select = "X"
    Start  = "V"
    A      = "T"
    B      = "E"

    [input.gamepad]
    # TODO
