name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup latest stable Rust toolchain
              run: |
                  rustup update stable
                  rustup component add rustfmt --target aarch64-unknown-linux-gnu
                  rustup default stable
                  rustup target add aarch64-unknown-linux-gnu
            - name: Setup libsdl2
              run: sudo apt-get -q update && sudo apt-get -q install -y \
                  libsdl2-dev \
                  libsdl2-ttf-dev
            - name: Tests
              run: cargo test -- --nocapture
