name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup libsdl2
        run: sudo apt-get -q update && sudo apt-get -q install -y \
          libsdl2-dev \
          libsdl2-ttf-dev
      - name: Tests
        run: cargo test -- --nocapture
